articles:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: articles
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - sqlite
      attach:
        - path: "md:articles"
          alias: articles
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: articles
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - sqlite
      attach:
        - path: "md:dev_articles"
          alias: articles
          is_ducklake: true
